"""created get all user post

Revision ID: 101394f3e62a
Revises: 92fa92f63125
Create Date: 2021-12-29 23:58:26.720054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101394f3e62a'
down_revision = '92fa92f63125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
