"""uploading image

Revision ID: 5afa8a37377e
Revises: 101394f3e62a
Create Date: 2021-12-30 01:45:41.520727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5afa8a37377e'
down_revision = '101394f3e62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('url_type', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_url')
    op.drop_column('posts', 'url_type')
    # ### end Alembic commands ###
